export const SUSPENSION_ERROR_MESSAGES = {
  USER_NOT_FOUND: 'User not found',
  ADMIN_CANNOT_BE_SUSPENDED: 'Admin users cannot be suspended',
  UNSUPPORTED_ROLE: 'Only customers, sellers, and delivery partners can be suspended',
  ALREADY_SUSPENDED: 'User is already suspended',
  USER_BLOCKED: 'A blocked user cannot be suspended',
  ACTIVE_SUSPENSION_EXISTS: 'User already has an active suspension',
  REASON_REQUIRED: 'Suspension reason is required',
  TEMPORARY_REQUIRES_EXPIRES_AT: 'Temporary suspension must have an expiration date',
  EXPIRES_AT_IN_PAST: 'Expiration date must be in the future',
  PERMANENT_NO_EXPIRES_AT: 'Permanent suspension should not have an expiration date',
  INVALID_USER_ID: 'Invalid user ID format',
  INVALID_SUSPENSION_TYPE: 'Invalid suspension type',
  SUSPENSION_CREATED: 'User suspended successfully',
  INVALID_SUSPENSION_ID: 'Invalid suspension ID format',
  SUSPENSION_NOT_FOUND: 'Suspension record not found',
  FORBIDDEN_APPEAL: 'You can only appeal your own suspension',
  INCONSISTENT_ROLE: 'User role is inconsistent with suspension role',
  SUSPENSION_NOT_ACTIVE: 'Suspension is not active',
  USER_NOT_SUSPENDED: 'User is not currently suspended',
  APPEAL_ALREADY_PENDING: 'An appeal is already pending for this suspension',
  APPEAL_ALREADY_SUBMITTED: 'An appeal has already been submitted for this suspension',
} as const;
